name: quickbill
description: "Generate invoice and keep track of payments and clients."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  get: ^4.7.2
  intl: ^0.20.2
  fl_chart: ^1.0.0
  http: ^1.4.0
  skeletonizer: ^2.0.1
  pinput: ^5.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_pdfviewer: ^30.2.5
  path_provider: ^2.1.5
  indian_currency_to_word: ^1.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.0
  open_filex: ^4.7.0
  file_saver: ^0.3.1
  device_info_plus: ^11.5.0
  expandable_page_view: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
